# Generated by Django 3.1.7 on 2021-02-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.URLField(blank=True, verbose_name='Источник'),
        ),
    ]
