# Generated by Django 3.1.7 on 2021-02-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0003_auto_20210222_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('wins', models.IntegerField(default=0, verbose_name='Победы')),
                ('losses', models.IntegerField(default=0, verbose_name='Поражения')),
                ('goals_scored', models.IntegerField(default=0, verbose_name='Заитые голы')),
                ('games_in_the_season', models.IntegerField(default=0, verbose_name='Игры в сезоне')),
            ],
            options={
                'verbose_name': 'Игровую статистику',
                'verbose_name_plural': 'Игровая статистика',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('educational_institution', models.CharField(max_length=40, verbose_name='Учебное заведение')),
                ('statistics', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='information_manager.gamestatistics', verbose_name='Игровая статистика')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=25, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=25, verbose_name='Отчество')),
                ('age', models.IntegerField(blank=True, verbose_name='Возраст')),
                ('playing_position', models.CharField(blank=True, max_length=25, verbose_name='Позиция')),
                ('is_captain', models.BooleanField(default=False, verbose_name='Капитан')),
                ('statistics', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='information_manager.gamestatistics', verbose_name='Игровая статистика')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='information_manager.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
