# Generated by Django 3.1.7 on 2021-02-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0004_gamestatistics_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='team',
            name='statistics',
        ),
        migrations.AddField(
            model_name='player',
            name='games_in_the_season',
            field=models.IntegerField(default=0, verbose_name='Игры в сезоне'),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_scored',
            field=models.IntegerField(default=0, verbose_name='Заитые голы'),
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0, verbose_name='Поражения'),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='Победы'),
        ),
        migrations.AddField(
            model_name='team',
            name='games_in_the_season',
            field=models.IntegerField(default=0, verbose_name='Игры в сезоне'),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_scored',
            field=models.IntegerField(default=0, verbose_name='Заитые голы'),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0, verbose_name='Поражения'),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='Победы'),
        ),
        migrations.DeleteModel(
            name='GameStatistics',
        ),
    ]
