# Generated by Django 3.1.7 on 2021-02-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0006_auto_20210225_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.FileField(blank=True, upload_to='players/', verbose_name='Фото'),
        ),
    ]
