# Generated by Django 3.1.7 on 2021-02-25 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0008_auto_20210225_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information_manager.team', verbose_name='Команда'),
        ),
    ]
