# Generated by Django 3.1.7 on 2021-02-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0009_auto_20210225_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('type_of_event', models.CharField(max_length=60, verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Тип мероприятие',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('date_of_the_event', models.DateTimeField(blank=True, verbose_name='Дата мероприятия')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('teams', models.ManyToManyField(blank=True, to='information_manager.Team', verbose_name='Команды')),
                ('type_of_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information_manager.typeofevent', verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
