# Generated by Django 3.1.7 on 2021-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0011_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(blank=True, choices=[('match', 'матч')], default='', max_length=150, verbose_name='Тип мероприятия'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TypeOfEvent',
        ),
    ]
