# Generated by Django 3.1.7 on 2021-03-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
        ('information_manager', '0012_auto_20210322_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users_for_notifications',
            field=models.ManyToManyField(to='tg_bot.TgUser', verbose_name='Пользователи для уведомлений'),
        ),
        migrations.AddField(
            model_name='event',
            name='users_for_text_translation',
            field=models.ManyToManyField(related_name='users_for_text_translation', to='tg_bot.TgUser', verbose_name='Пользователи для текстовой трансляции'),
        ),
    ]
