# Generated by Django 3.1.7 on 2021-03-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0017_auto_20210327_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstaff',
            name='goals_scored',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голы'),
        ),
        migrations.AlterField(
            model_name='coachingstaff',
            name='goalscoring_matches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голевые матчи'),
        ),
        migrations.AlterField(
            model_name='coachingstaff',
            name='losses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поражения'),
        ),
        migrations.AlterField(
            model_name='coachingstaff',
            name='wins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Победы'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голевые передачи'),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals_scored',
            field=models.IntegerField(blank=True, null=True, verbose_name='Забитые голы'),
        ),
        migrations.AlterField(
            model_name='player',
            name='losses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поражения'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Победы'),
        ),
    ]
