# Generated by Django 3.1.7 on 2021-03-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
        ('information_manager', '0018_auto_20210327_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='SentNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_manager.news', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.tguser', verbose_name='Телеграм пользователь')),
            ],
            options={
                'verbose_name': 'Отправленные новости',
                'verbose_name_plural': 'Отправленная новость',
                'ordering': ('-update_date',),
            },
        ),
    ]
