# Generated by Django 3.1.7 on 2021-03-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0020_auto_20210327_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentnews',
            name='created_via_telegram',
            field=models.BooleanField(default=False, verbose_name='Создано через телеграм'),
        ),
    ]
