# Generated by Django 3.1.7 on 2021-03-28 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0023_auto_20210327_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
