# Generated by Django 3.1.7 on 2021-03-28 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_admin_bot', '0003_delete_adminnews'),
        ('information_manager', '0024_auto_20210328_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='telegram_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tg_admin_bot.tgadminuser', verbose_name='Телеграм автор'),
        ),
    ]
