# Generated by Django 3.1.7 on 2021-03-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_admin_bot', '0004_auto_20210328_1031'),
        ('information_manager', '0025_news_telegram_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='telegram_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_admin_bot.tgadminuser', verbose_name='Телеграм автор'),
        ),
    ]
