# Generated by Django 3.1.7 on 2021-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager', '0027_auto_20210328_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingstaff',
            name='goalscoring_matches',
        ),
        migrations.RemoveField(
            model_name='coachingstaff',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='coachingstaff',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='player',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wins',
        ),
        migrations.AddField(
            model_name='coachingstaff',
            name='assists',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голевые передачи'),
        ),
        migrations.AddField(
            model_name='coachingstaff',
            name='number_of_matches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество матчей'),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_matches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество матчей'),
        ),
    ]
