# Generated by Django 3.1.7 on 2021-03-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=8)),
                ('is_used', models.BooleanField(default=False, verbose_name='Ипользовано')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания аккаунта')),
            ],
            options={
                'verbose_name': 'Токен администратора',
                'verbose_name_plural': 'Токены администраторов',
            },
        ),
        migrations.CreateModel(
            name='TgAdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('username', models.CharField(max_length=60)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания аккаунта')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tg_admin_bot.adminusertoken', verbose_name='Токен регистрации')),
            ],
            options={
                'verbose_name': 'Телеграм админ',
                'verbose_name_plural': 'Телеграм админ',
            },
        ),
    ]
