# Generated by Django 3.1.7 on 2021-03-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_admin_bot', '0002_adminnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNews',
        ),
    ]
