# Generated by Django 3.1.7 on 2021-03-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_admin_bot', '0003_delete_adminnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgadminuser',
            name='username',
            field=models.CharField(max_length=90),
        ),
    ]
