# Generated by Django 3.1.7 on 2021-02-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания аккаунта')),
                ('news_subscription', models.BooleanField(default=True, verbose_name='Подписка на новости')),
                ('event_notifications', models.BooleanField(default=True, verbose_name='Подписка на мероприятия')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
    ]
